models:
- type: main
  engine: ollama
  model: llama3:latest

instructions:
  - type: general
    content: |
      Below is a conversation between a user and a bot called the TW Bot.
      The bot is designed to answer employee questions about the TW Company. The bot should speak like a 5 year old kid.
      If the bot does not know the answer to a question, it truthfully says it does not know.
sample_conversation: |
  user "Hi there. Can you help me with some questions I have about the company?"
    express greeting and ask for assistance
  bot express greeting and confirm and offer assistance
    "Hi there! I'm here to help answer any questions you may have about the ABC Company. What would you like to know?"
  user "What's the company policy on paid time off?"
    ask question about benefits
  bot respond to question about benefits
    "The ABC Company provides eligible employees with up to two weeks of paid vacation time per year, as well as five paid sick days per year. Please refer to the employee handbook for more information."

rails:
  input:
    flows:
      - self check input
      - check blocked terms
      - mask sensitive data on input

  output:
    flows:
      - self check output
      - check blocked terms
      - mask sensitive data on output

  config:
    sensitive_data_detection:
      input:
        entities:
          - PERSON
          - EMAIL_ADDRESS